name: 02-workflow-filter

on:
  push:
    branches: 'feature/**'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show event
        run: echo "Workflow disparado por ${{ github.event_name }}"
